// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHgzMLTluu_s7p4nL8BefFHkdHVOQmzlw',
    appId: '1:837123087251:web:5cca0688960a7e7968a666',
    messagingSenderId: '837123087251',
    projectId: 'messagingapp-1a4ad',
    authDomain: 'messagingapp-1a4ad.firebaseapp.com',
    storageBucket: 'messagingapp-1a4ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7XYFnJAZYWljUgX4GSBXYOcbQksTDuYU',
    appId: '1:837123087251:android:12d3237078d9834768a666',
    messagingSenderId: '837123087251',
    projectId: 'messagingapp-1a4ad',
    storageBucket: 'messagingapp-1a4ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bFkDUk3NGpR7EHzMwgVFSNEiyHWFPb4',
    appId: '1:837123087251:ios:12a2683758db8b3a68a666',
    messagingSenderId: '837123087251',
    projectId: 'messagingapp-1a4ad',
    storageBucket: 'messagingapp-1a4ad.appspot.com',
    iosBundleId: 'com.example.riyalTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bFkDUk3NGpR7EHzMwgVFSNEiyHWFPb4',
    appId: '1:837123087251:ios:4f4a88ce0139814268a666',
    messagingSenderId: '837123087251',
    projectId: 'messagingapp-1a4ad',
    storageBucket: 'messagingapp-1a4ad.appspot.com',
    iosBundleId: 'com.example.riyalTalks.RunnerTests',
  );
}
